---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [4]:
pwd

'C:\\Users\\SU25452\\Documents\\Coursera-Python\\course1_downloads'

In [1]:
cd course1_downloads

C:\Users\SU25452\Documents\Coursera-Python\course1_downloads

In [10]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='â„–':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [6]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [12]:
df['Gold'].max()

976

In [11]:
def answer_one():
    return df[df['Gold'] == df['Gold'].max()].index[0]

answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [15]:
df.loc['United States']

# Summer              26
Gold                 976
Silver               757
Bronze               666
Total               2399
# Winter              22
Gold.1                96
Silver.1             102
Bronze.1              84
Total.1              282
# Games               48
Gold.2              1072
Silver.2             859
Bronze.2             750
Combined total      2681
ID                   USA
goldsummwintdiff     880
Name: United States, dtype: object

In [13]:
def answer_two():
    df['goldsummwintdiff'] = df['Gold'] - df['Gold.1']
    return df[df['goldsummwintdiff'] == df['goldsummwintdiff'].abs().max()].index[0]

answer_two()

'United States'

In [18]:
df['goldsummwintdiff'].abs().idxmin()

'Afghanistan'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [16]:
def answer_three():
    df["goldsummwintpercentdiff"] = (df["Gold"] - df["Gold.1"])/ (df["Gold"] + df["Gold.1"])
    return df["goldsummwintpercentdiff"].idxmax()

answer_three()

'Algeria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [34]:
def answer_four():
    #return pd.Series(data=df["Gold.2"]*3 + df["Silver.2"]*2 + df["Bronze.2"], name='Points')
    df["Points"] = df["Gold.2"]*3 + df["Silver.2"]*2 + df["Bronze.2"]
    return df["Points"]

type(answer_four())

pandas.core.series.Series

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [3]:
import pandas as pd

In [4]:
census_df = pd.read_csv('census.csv')
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [6]:
census_df['STNAME'].value_counts()

Texas                   255
Georgia                 160
Virginia                134
Kentucky                121
Missouri                116
Kansas                  106
Illinois                103
North Carolina          101
Iowa                    100
Tennessee                96
Nebraska                 94
Indiana                  93
Ohio                     89
Minnesota                88
Michigan                 84
Mississippi              83
Oklahoma                 78
Arkansas                 76
Wisconsin                73
Pennsylvania             68
Alabama                  68
Florida                  68
South Dakota             67
Colorado                 65
Louisiana                65
New York                 63
California               59
Montana                  57
West Virginia            56
North Dakota             54
South Carolina           47
Idaho                    45
Washington               40
Oregon                   37
New Mexico               34
Utah                     30
Alaska                   30
Maryland                 25
Wyoming                  24
New Jersey               22
Nevada                   18
Maine                    17
Arizona                  16
Vermont                  15
Massachusetts            15
New Hampshire            11
Connecticut               9
Rhode Island              6
Hawaii                    6
Delaware                  4
District of Columbia      2
Name: STNAME, dtype: int64

In [10]:
def answer_five():
    return (census_df[census_df['SUMLEV']==50].groupby(['STATE']).count())

answer_five()

,SUMLEV,REGION,DIVISION,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STATE,,,,,,,,,,,,,,,,,,,,,
1,67,67,67,67,67,67,67,67,67,67,...,67,67,67,67,67,67,67,67,67,67
2,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,29,29
4,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
5,75,75,75,75,75,75,75,75,75,75,...,75,75,75,75,75,75,75,75,75,75
6,58,58,58,58,58,58,58,58,58,58,...,58,58,58,58,58,58,58,58,58,58
8,64,64,64,64,64,64,64,64,64,64,...,64,64,64,64,64,64,64,64,64,64
9,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
10,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
11,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
12,67,67,67,67,67,67,67,67,67,67,...,67,67,67,67,67,67,67,67,67,67
13,159,159,159,159,159,159,159,159,159,159,...,159,159,159,159,159,159,159,159,159,159
15,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
16,44,44,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
17,102,102,102,102,102,102,102,102,102,102,...,102,102,102,102,102,102,102,102,102,102
18,92,92,92,92,92,92,92,92,92,92,...,92,92,92,92,92,92,92,92,92,92
19,99,99,99,99,99,99,99,99,99,99,...,99,99,99,99,99,99,99,99,99,99
20,105,105,105,105,105,105,105,105,105,105,...,105,105,105,105,105,105,105,105,105,105
21,120,120,120,120,120,120,120,120,120,120,...,120,120,120,120,120,120,120,120,120,120
22,64,64,64,64,64,64,64,64,64,64,...,64,64,64,64,64,64,64,64,64,64
23,16,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
24,24,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,24,24,24
25,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
26,83,83,83,83,83,83,83,83,83,83,...,83,83,83,83,83,83,83,83,83,83
27,87,87,87,87,87,87,87,87,87,87,...,87,87,87,87,87,87,87,87,87,87
28,82,82,82,82,82,82,82,82,82,82,...,82,82,82,82,82,82,82,82,82,82
29,115,115,115,115,115,115,115,115,115,115,...,115,115,115,115,115,115,115,115,115,115
30,56,56,56,56,56,56,56,56,56,56,...,56,56,56,56,56,56,56,56,56,56
31,93,93,93,93,93,93,93,93,93,93,...,93,93,93,93,93,93,93,93,93,93
32,17,17,17,17,17,17,17,17,17,17,...,17,17,17,17,17,17,17,17,17,17
33,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
34,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,21,21,21
35,33,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,33,33,33
36,62,62,62,62,62,62,62,62,62,62,...,62,62,62,62,62,62,62,62,62,62
37,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
38,53,53,53,53,53,53,53,53,53,53,...,53,53,53,53,53,53,53,53,53,53
39,88,88,88,88,88,88,88,88,88,88,...,88,88,88,88,88,88,88,88,88,88
40,77,77,77,77,77,77,77,77,77,77,...,77,77,77,77,77,77,77,77,77,77
41,36,36,36,36,36,36,36,36,36,36,...,36,36,36,36,36,36,36,36,36,36
42,67,67,67,67,67,67,67,67,67,67,...,67,67,67,67,67,67,67,67,67,67
44,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
45,46,46,46,46,46,46,46,46,46,46,...,46,46,46,46,46,46,46,46,46,46
46,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66
47,95,95,95,95,95,95,95,95,95,95,...,95,95,95,95,95,95,95,95,95,95
48,254,254,254,254,254,254,254,254,254,254,...,254,254,254,254,254,254,254,254,254,254
49,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,29,29
50,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
51,133,133,133,133,133,133,133,133,133,133,...,133,133,133,133,133,133,133,133,133,133
53,39,39,39,39,39,39,39,39,39,39,...,39,39,39,39,39,39,39,39,39,39
54,55,55,55,55,55,55,55,55,55,55,...,55,55,55,55,55,55,55,55,55,55
55,72,72,72,72,72,72,72,72,72,72,...,72,72,72,72,72,72,72,72,72,72
56,23,23,23,23,23,23,23,23,23,23,...,23,23,23,23,23,23,23,23,23,23

In [28]:
dfTrimmed = census_df[census_df['SUMLEV']==50][['STNAME','CENSUS2010POP']].set_index('STNAME')
stgrp = dfTrimmed.groupby(['STNAME'])
    
#for each state get 3 most populous states and sum the populations
dfTop3CountyPop = stgrp.apply(lambda x: x.nlargest(3, 'CENSUS2010POP').sum())

dfTop3CountyPop.nlargest(3, 'CENSUS2010POP').sort_values('CENSUS2010POP',ascending=False).index.tolist()

['California', 'Texas', 'Illinois']

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [24]:
dfTrimmed = census_df[census_df['SUMLEV']==50][['STNAME','CENSUS2010POP']].set_index('STNAME')

In [25]:
def answer_six():
    #return census_df[census_df['SUMLEV']==50].groupby(['STATE']).max().sort_values('CENSUS2010POP',ascending=False)[:3]['STNAME'].tolist()
    #group by state
    dfTrimmed = census_df[census_df['SUMLEV']==50][['STNAME','CENSUS2010POP']].set_index('STNAME')
    stgrp = dfTrimmed.groupby(['STNAME'])
    
    #for each state get 3 most populous states and sum the populations
    dfTop3CountyPop = stgrp.apply(lambda x: x.nlargest(3, 'CENSUS2010POP').sum())
    
    #Get top 3 states by population
    Top3States = dfTop3CountyPop.nlargest(3, 'CENSUS2010POP').sort_values('CENSUS2010POP',ascending=False).index.tolist()
    return Top3States
  
answer_six()

['California', 'Texas', 'Illinois']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [114]:
def answer_seven():
    dfpop = (census_df[census_df['SUMLEV']==50])[['COUNTY','CTYNAME','POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']]
    dfpop['max'] = dfpop.max(axis=1)
    dfpop['min'] = dfpop.min(axis=1)
    dfpop['change'] = dfpop['max']-dfpop['min']
    return dfpop.iloc[dfpop['change'].abs().idxmax()]['CTYNAME']

answer_seven()

'Merced County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [142]:
def answer_eight():
    return census_df[census_df['REGION'].isin([1,2]) & census_df['CTYNAME'].str.startswith('Washington') & (census_df['POPESTIMATE2015'] > census_df['POPESTIMATE2014'])].sort_index()[['STNAME','CTYNAME']]

answer_eight()

            STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County